SPK_NAME = racket
SPK_VERS = 7.9
SPK_REV = 1
SPK_ICON = src/racket.png

DEPENDS = cross/racket

MAINTAINER = SynoCommunity
DESCRIPTION = Racket programming language - minimal installation.age.
DISPLAY_NAME = Racket
RELOAD_UI = no
STARTABLE = no
CHANGELOG = "first issue"

HOMEPAGE = https://racket-lang.org/
LICENSE = MIT

SPK_COMMANDS = bin/racket

include ../../mk/spksrc.spk.mk
